version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install -q
  snyk_code_test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - checkout
    - run:
        command: | 
          snyk auth $SNYK_TOKEN
          snyk code test || true
  snyk_oss_test:
    docker:
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - snyk/scan:
        token-variable: SNYK_TOKEN
        fail-on-issues: false
        monitor-on-build: false      
  docker_build_push:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$pipeline.number
          docker build -t $DOCKER_USERNAME/docker-goof:$TAG .
          docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/docker-goof:$TAG 
  snyk_container_test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - checkout
    - run:
        command: | 
          snyk auth $SNYK_TOKEN
          snyk container test jiajunngjj/docker-goof --file=./Dockerfile || true
  trigger_argocd:
    docker:
      - image: cimg/base:2022.04
    steps:
      - run : |
          TAG=0.1.$pipeline.number
          git clone https://github.com/jiajunngjj/circleci-argocd-goof.git
          cd circleci-argocd-goof
          sed -i 's/\(docker-goof\)\(.*\)/\1:'$TAG'/' goof/goof-deployment.yaml
          git config user.email "ngjiajun13@gmail.com"
          git config user.name "jiajunngjj"
          git add goof/goof-deployment.yaml
          git commit -m "update from circleci to trigger argocd"
          git push https://$GITHUB_PERSONAL_TOKEN@github.com/jiajunngjj/circleci-argocd-goof.git 
workflows:
  build_and_test:
    jobs:
      - build
      - snyk_code_test:
          requires:
            - build
      - snyk_oss_test:
          requires:
            - build
      - docker_build_push:
          requires:
            - snyk_code_test
            - snyk_oss_test
      - snyk_container_test:
          requires:
            - docker_build_push
      - trigger_argocd:
          requires:
            - snyk_container_test
